language: python
sudo: false 
dist: trusty
python:
  - "2.7"
env:
  # This environment variable tells Terraform not to prompt for input. This is
  # not required, but if we make a mistake, the Travis builder will hang waiting
  # for user input, tieing up unnecessary resources.
  - TF_INPUT=false

before_install:
- pip install awscli
- curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
- unzip /tmp/terraform_0.11.7_linux_amd64.zip -d /tmp
- chmod 755 /tmp/terraform
- mkdir ~/bin
- export PATH="~/bin:$PATH"
- mv /tmp/terraform ~/bin/
- cd terraform
- ./tf.sh

script:
- terraform plan

deploy:
- provider: script
  skip_cleanup: true
  script: terraform apply -auto-approve
  on:
    branch: master
